name: Build

on:
  push:
    branches: [ master ]
    paths:
      - "app/**"
      - "Dockerfile"
      - "pyproject.toml"

jobs:
  build:
    uses: your-username/devops-actions/.github/workflows/reusable-build.yml@master
    with:
      image_name: your-dockerhub-username/service-b
